version: '3'
tasks:
  build:
    cmds:
      - cmd: go generate ./...
      - cmd: go build -ldflags="-s -w" -o bin/recipya.exe main.go
        platforms: [ windows ]
      - cmd: go build -ldflags="-s -w" -o bin/recipya main.go
        platforms: [ linux, darwin ]

  build-debug:
    cmds:
      - cmd: go generate ./...
      - cmd: go build -gcflags=all="-N -l" -o bin/recipya_debug.exe main.go
        platforms: [ windows ]
      - cmd: go build -gcflags=all="-N -l" -o bin/recipya_debug main.go
        platforms: [ linux, darwin ]

  cover:
    cmds:
      - cmd: go test ./... -coverprofile=coverage.out
      - cmd: go tool cover -html=coverage.out -o coverage.html
      - cmd: rm coverage.out

  new-migration:
    requires:
      vars: [ name ]
    cmd: cd internal/services/migrations && goose create {{.name}} sql

  release:
    deps:
      - test
    requires:
      vars: [ tag ]
    cmds:
      - go run ./releases/main.go -package github.com/reaper47/recipya -tag {{.tag}}
      - gh release create {{.tag}} ./releases/{{.tag}}/*

  run:
    deps:
      - build
    cmd: ./bin/recipya serve

  sponsors:
    cmds:
      - cmd: cd ./scripts/sponsors
      - cmd: npm i
      - cmd: npx sponsorkit -o ../../docs/website/static/images/

  test:
    deps:
      - build
    cmd: go test ./...

  test-no-build:
    cmd: go test ./...
