name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set base path
        run: echo "BASE_PATH=$GITHUB_WORKSPACE/docs/website" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: './docs/website/package-lock.json'

      - name: Install dependencies
        run: |
          cd $BASE_PATH
          yarn install --frozen-lockfile

      - name: Build website
        run: |
          cd $BASE_PATH
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/website/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com