name: trigger-nightly

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  nightly:
    name: Nightly
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: |
          cd ./releases
          go run main.go -package github.com/reaper47/recipya -tag nightly

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: nightly
          prerelease: true
          title: Nightly
          files: ./releases/nightly/*.zip

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: reaper99/recipya@nightly

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./containers/Dockerfile
          push: true
          tags: reaper99/recipya:nightly
          labels: ${{ steps.meta.outputs.labels }}